spring.application.name=entradas

# 1. DESACTIVAR el control automatico de Docker (para usar el tuyo manual)
spring.docker.compose.enabled=false

# 2. CONEXION AL PUERTO 5433 (El que pusimos en el yaml)
spring.datasource.url=jdbc:postgresql://localhost:5433/cinedb
spring.datasource.username=admin
spring.datasource.password=password123
spring.datasource.driver-class-name=org.postgresql.Driver

# 3. CREACION DE TABLAS (Vital para que no falle el Seeder)
spring.jpa.hibernate.ddl-auto=update

# 4. Ver las consultas en consola (Opcional, ayuda a depurar)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect