spring.application.name=cursoSpringBoot
#Para cambiar el puerto usaremos: server.port=8081

# Esto sirve para poner el JSON bonito al acceder a la INFO, otra forma es con la extension JSON formatter
# spring.jackson.serialization.indent_output=true